### ISSUE TITLE
Adopt mise as an option for language runtime management

### ISSUE THREAD

**Issue by maxfierke** [maxfierke/mstrap#51]
[`mise`](https://mise.jdx.dev/) f.k.a. `rtx` carries a number of benefits or additional features over `asdf`, namely some performance improvements, built-in language runtime version management support (e.g. no plugins needed for Ruby), fast native binaries, and `direnv` & `make`-like capabilities

**Describe the solution you'd like**

Creating configurable runtime manager abstraction to allow `mise` to be used as the runtime manager for language runtimes in projects setup by `mstrap`. This structure could in the future allow for potentially adopting other (or multiple) runtime managers (e.g. using `rustup` for Rust, `mise` for others, etc.)

**Describe alternatives you've considered**

Continuing w/ the `asdf` integration as-is

**Describe how this fits in with the project's aims** (as described [here](https://mstrap.dev/docs/))

Mise is an opinionated tool whose opinions align well w/ `mstrap` aims so far. The `direnv`-like environment variable management and task runner capabilities could be useful to build off of in the future (e.g. calling specific hooks defined as `mise` tasks or setting up project environment variables)

**Additional context**

Ultimately, I'd like to move to `mise` becoming the default, but for now it will be opt-in via a setting in `config.hcl` for experimentation. Continuing w/ `asdf` as a default is an option, if for some reason `mise` appears not to be a suitable default.

**Checklist**
- [X] I have read the [project aims](https://mstrap.dev/docs/) on the documentation site
- [X] To the best of my knowledge, I am not asking about an existing feature request

### TODO

- [X] `RuntimeManager` abstraction && `mise` `RuntimeManager` implementation (#50)
- [ ] #52
- [ ] Document config schema changes
